### ISSUE TITLE
Cannot select multiple categories to 3d plot...

### ISSUE THREAD

**Issue by mazepse** [JanMarvin/RQDA#13]
I followed the above instructions: 
- installed rqda successfully on win10/64bit using rstudio 1.3.959 [5* kudos Jan!]
- loaded project in [qdas.uom.gr/wp-content/uploads/2019/10/PRJ01.zip](url) fine

when trying to  d3network plot the categories, and while choosing... my console showed:
Error: Expecting a single string value: [type=character; extent=2].

Also, in a subsequent run, i tried to simple plot (not 3d) only one category and rstudio crushed (showing the abortion bomb pic)

any hint will be greatly appreciated!

**Comment by JanMarvin** [comment]
I'll look into it. Thanks for the report. I assume it has been working before (e.g., it's not a feature request but something you have seen working)?

**Comment by mazepse** [comment]
Thanks, Jan, for the immediate response!
RQDA has been incorporated to many books and articles as well as full courses and this depreciation is very costly in time invested. Anyway,
After loading the PRJ01.rqda project, 
I select CodeCategories and pick all available categories. While I pick more than one category (2nd and 3rd here), and in each successive pick I get 

Error: Expecting a single string value: [type=character; extent=2].
Error: Expecting a single string value: [type=character; extent=3].

in the console, and no graph is created, of course, after issuing the command “Plot selected … 3d”   from the context sensitive menu since no selection is valid.
The necessary packages are loaded. I believe it has something to do with the category selection function.
Thanks again for your help and interest!
M.

**Comment by JanMarvin** [comment]
> Thanks, Jan, for the immediate response!
> RQDA has been incorporated to many books and articles as well as full courses and this depreciation is very costly in time invested.

Just so you know, I don't actually gain anything from my invested time but internet points.

> Anyway,
> After loading the PRJ01.rqda project,
> I select CodeCategories and pick all available categories. While I pick more than one category (2nd and 3rd here), and in each successive pick I get
> 
> Error: Expecting a single string value: [type=character; extent=2].
> Error: Expecting a single string value: [type=character; extent=3].
> 
> in the console, and no graph is created, of course, after issuing the command “Plot selected … 3d” from the context sensitive menu since no selection is valid.
> The necessary packages are loaded. I believe it has something to do with the category selection function.
> Thanks again for your help and interest!
> M.

I'll look into it. Since I wasn't aware of this feature, I've probably removed it unknowingly.

**Comment by mazepse** [comment]
There is no solution?

**Comment by JanMarvin** [comment]
I have pushed a fix. Please check if that solves your problem. I can create graphs from multiple coding categories using d3Network and igraph. You have to select them and afterwards click somewhere else with the right mouse button to select the plots. Otherwise RQDA will lose focus.
