### ISSUE TITLE
Windows install does not work

### ISSUE THREAD

**Issue by sonyapdichal** [JanMarvin/RQDA#8]
When I tried your devtools installtion i am getting this response. please help

   
Installing package into ‘C:/Users/HP/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'RQDA' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'RSQLite' was built under R version 3.6.3
Execution halted
ERROR: lazy loading failed for package 'RQDA'
* removing 'C:/Users/HP/Documents/R/win-library/3.6/RQDA'
Error: Failed to install 'RQDA' from GitHub:
  (converted from warning) installation of package ‘C:/Users/HP/AppData/Local/Temp/RtmpA9xFRd/file45941cee52b1/RQDA_0.3-2.tar.gz’ had non-zero exit status

**Comment by JanMarvin** [comment]
Hi @sonyapdichal could you please upload a full buildlog and provide some information regarding your build environment? Sys.info() maybe? Thanks

**Comment by sonyapdichal** [comment]
Hi @JanMarvin

 Sys.info()
       sysname        release        version       nodename        machine 
     "Windows"       "10 x64"  "build 18362"       "SONYHP"       "x86-64" 
         login           user effective_user 
          "HP"           "HP"           "HP" 
> 
 sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):

**Comment by JanMarvin** [comment]
And the buildlog? Your R installation is a bit dated, but that doesn't matter. You should install the required packages RSQLite, Rgtk2 etc. and afterwards run the devtools command with the "--no-multiarch" option

**Comment by sonyapdichal** [comment]
@JanMarvin What is build log? I am a social science researcher. Not into coding. I had the new  R (4.0) since the RQDA was not working there, I thought I will try with older version

**Comment by JanMarvin** [comment]
A build log is the output of the devtools command. If you have R 4.0 around I'd work with that. Anyways for now all I now is that your installation did not succeed.

**Comment by sonyapdichal** [comment]
I have R 4.0.1. I can install that. can you help me with installing RQDA, please?

**Comment by JanMarvin** [comment]
Well yeah, that's what I'm trying to do ☺️ But for that to work I need you to let me help you, e.g. by providing a build log

**Comment by sonyapdichal** [comment]
THank you. Sure. I will install R. 4.0 now. and then I will install devtools by following your code. is that okay. and how to find the build log?

**Comment by JanMarvin** [comment]
Start R (I work with the latest release 4.0.1 but it does not really matter (sorry if I confused you, just woke up)).

Install the required packages:
```{r}
# packages you need to run and build RQDA
pkgs <- c("RSQLite", "gWidgets2RGtk2", "DBI",
          "stringi", "RGtk2", "igraph", "gWidgets2", "devtools")

# install these
install.packages(pkgs)

# run this once and click OK when asked to install Gtk2
library(RGtk2)

# run this command once, if it fails, copy the output of your R instance to let me see what's going on
devtools::install_github("JanMarvin/RQDA", INSTALL_opts = "--no-multiarch")
```

**Comment by JanMarvin** [comment]
Once this is done, **please be aware that this package is still experimental**. I'm fairly certain that it works as expected, but if you're working on something important, please make a backup of the rqda files you're about to open

**Comment by smacsween** [comment]
Thank you - this worked for me once I had updated R to 4.0.1 and installed the packages above.

**Comment by sonyapdichal** [comment]
Thank you so much. I could successfully install RQDA by following your instructions. Everthing is working perfectly except the files imported to the RQDA is not able to open. I tried with importing new files. though it is appearing in the files list, it is not opening. I got the following messages in the R 
> library (RQDA)
Loading required package: RSQLite
Loading required package: gWidgets2RGtk2
Loading required package: memoise
Loading required package: RGtk2
Loading required package: gWidgets2
Loading required package: digest
Loading required package: DBI
Loading required package: stringi

Use 'RQDA()' to start the programme.

File imported with the following encoding:  windows-1252 
File imported with the following encoding:  windows-1252 
File imported with the following encoding:  windows-1252

**Comment by JanMarvin** [comment]
@sonyapdichal ah yes, sorry, they open, but they open on a second screen or something like that (I usually work on Linux with a tiling window manager and do not see this issues there).  I'll push a fix and notify once this is fixed

**Comment by JanMarvin** [comment]
This is fixed in https://github.com/JanMarvin/RQDA/commit/051849a764f4b26717810ccc3fd7a28e738763db you need to run devtools again

```{r}
devtools::install_github("JanMarvin/RQDA", INSTALL_opts = "--no-multiarch")
```

**Comment by JanMarvin** [comment]
Closing as the initial issue was solved

**Comment by sonyapdichal** [comment]
@JanMarvin  Thanks a ton! The files also opening now. thanks for your help
